import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ActualProfilePic from "@/components/actualProfilePic.js";  // Importamos la foto de perfil

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}