import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <header>
          <Link href="/chats">
          <h1>Whatsapp</h1>
          </Link>
        </header>
        {children}
        <footer> sos un cabeza</footer>
      </body>
    </html>
  );
}